const ApiList = {
    checkAuth: '/admin/check',
    login: "/admin/auth/login",
    CilentsList: "/admin/users/view",
    BlockClient: "/admin/users/block",
    ActivateClients: "/admin/users/active",
    EditClients: "/admin/users/edit",
    AddClients: "/admin/users/create",
    AdminsList: "/admin/view",
    BlockAdmin: "/admin/block",
    activateAdmin: "/admin/active",
    getPermissions: "/admin/get_permissions",
    AddAdmin: "/admin/create",
    EditAdmin: "/admin/edit",
    getAdminPermissions: "/admin/get_admin_permissions",
    editUserPassword: "/admin/users/reset_password",
    editAdminPassword: "/admin/password",
    editAdminPermissions: "/admin/edit_permissions",
    getServices: "/admin/services/view",
    activateService: "/admin/services/activate",
    editService: "/admin/services/edit",
    getProviders: "/admin/providers/view",
    activateProviders: "/admin/providers/activate",
    deleteProviders: "/admin/providers/delete",
    getAllServices: "/admin/providers/services",
    editProviders: "/admin/providers/edit",
    getCompanyInfo: "/admin/settings/company/view",
    editCompanyInfo: "/admin/settings/company/edit",
    getCities: "/admin/settings/city/view",
    activateCities: "/admin/settings/city/activate",
    editCities: "/admin/settings/city/edit",
    getReasons: "/admin/settings/reasons/view",

}

export default ApiList